### ISSUE TITLE
Transforme este repo num live-demo usando github pages

### ISSUE THREAD

**Issue by tonylampada** [tiagocedrim/angularjsNaPratica#1]
Se vc colocar esse repositorio numa branch chamada gh-pages ao inves de master, ele ficará publicado no github.io.
Mais legal assim :-)

https://help.github.com/articles/creating-project-pages-manually/

**Comment by titxoo** [comment]
@tonylampada Brigado pela dica, me inspirei no seu projeto para fazer o meu. vou fazer isso meu caro. Vlw mesmo.

**Comment by titxoo** [comment]
@tonylampada Feito =D

**Comment by tonylampada** [comment]
woooow daoraaaa
http://tiagocedrim.github.io/angularjsNaPratica/

:-)
